[package]
name = "rust-vmaf-sys"
version = "0.2.0"
edition = "2021"
authors.workspace = true
license.workspace = true
description = """
Exported bindings for the libvmaf.
"""

[lints]
workspace = true

[build-dependencies]
bindgen = { version = "0.69.4" }
